#!/bin/bash

file=$1
outfile=$2
objdump -d $file | grep "<.text>" | sed 's/^\([0-9a-f]*\).*/\1/'

objdump -d $file | grep "^ " | sed 's/.*:\t\(.\{15\}\).*/\1/' > $file.hex
writehex2 $file.hex > $file.bin

