#!/bin/bash

ulimit -s 262144
folder=$1
ep=`python2 ../pe.py $folder/$folder.snapshot0 entrypoint 2>/dev/null`
baseaddr=`python2 ../pe.py $folder/$folder.snapshot0 baseaddr 2>/dev/null`

echo "ep: "$ep", baseaddr: "$baseaddr
n_trace=`tail -n 1 $folder/$folder".trace" |sed 's/_.*//'`

if [ -z $ep ]; then
  touch $folder/notpe
  echo "error: notpe"
elif [ -e $folder/error ]; then
  echo "error: skipping"
elif [ -e $folder/disasm ]; then
  echo "disasm: skipping"
else
  for i in `seq 0 $n_trace`; do
    rm -f file.dot
    n=`printf "%02d" $i`
    snapshot=$folder/$folder.snapshot$i
    w_trace=$folder/$folder.trace-w$n
    #echo $snapshot" "$baseaddr" 0 "$baseaddr" "$ep" "$w_trace" dump"
    echo "processing wave "$n
    #python2 ../from-traces/overlap.py $folder/$folder.size-w$n -v > $folder/$folder"_"$n.c_trace
    #n_conflicts_trace=`cat $folder/$folder"_"$n.c_trace|head -n 1 | sed 's/\ .*//'`
    #echo $n_conflicts_trace" conflicts in trace."
    set -o xtrace
    timefile=$folder/$folder"_"$n.time
    /usr/bin/time -f %E -o $timefile python2 ../disasm.py $snapshot $baseaddr 0 $baseaddr $ep $w_trace $folder/$folder.trace dump opcodes.prob usetrace > $folder/$folder"_"$n.log 2>$folder/$folder"_"$n.err
    set +o xtrace
    n_conflicts_disasm=`grep remain $folder/$folder"_"$n.log | sed 's/\ .*//'`
    echo $n_conflicts_disasm" conflicts in disasm."
    mv file.dot $folder/$folder"_"$n.dot
  done
  touch $folder/disasm
fi

echo ""
