#!/bin/bash

folder=$1
ep=`python2 ../pe.py $folder/$folder.snapshot0 entrypoint`
baseaddr=`python2 ../pe.py $folder/$folder.snapshot0 baseaddr`

echo "ep: "$ep", baseaddr: "$baseaddr
n_trace=`tail -n 1 $folder/$folder".trace" |sed 's/_.*//'`

if [ -e $folder/error ]; then
  echo "error: skipping"
elif [ -e $folder/disasm ]; then
  echo "disasm: skipping"
else
  for i in `seq 0 $n_trace`; do
    n=`printf "%02d" $i`
    snapshot=$folder/$folder.snapshot$i
    w_trace=$folder/$folder.trace-w$n
    #echo $snapshot" "$baseaddr" 0 "$baseaddr" "$ep" "$w_trace" dump"
    echo "processing wave "$n
    python2 ../from-traces/overlap.py $folder/$folder.size-w$n -v > $folder/$folder"_"$n.c_trace
    n_conflicts_trace=`cat $folder/$folder"_"$n.c_trace|head -n 1 | sed 's/\ .*//'`
    echo $n_conflicts_trace" conflicts in trace."
    python2 ../disasm.py $snapshot $baseaddr 0 $baseaddr $ep $w_trace $folder/$folder.trace dump > $folder/$folder"_"$n.log 2>$folder/$folder"_"$n.err
    n_conflicts_disasm=`grep remain $folder/$folder"_"$n.log | sed 's/\ .*//'`
    echo $n_conflicts_disasm" conflicts in disasm."
    mv file.dot $folder/$folder"_"$n.dot
  done
  touch $folder/disasm
fi

echo ""
