#!/bin/bash

list=`ls | grep tar | sed 's/\.tar.*//'`

echo "nW: number of waves"
echo "iW: current wave"
echo "nld(t): number of layers in disasm (resp. in trace)"
echo "njd(t): number of misaligned jumps in disasm (resp. in trace)"
echo "ncd(t): number of conflicts in disasm (resp. in trace)"
echo "nacd(t): number of addresses in conflict in disasm (resp. in trace)"
l="sample\t\t\t\t\t\t\t\t\tnW\tiW\tnld(t)\tnjd(t)\tncd(t)\tnacd(t)"
echo -e $l
for i in `echo $list`; do
  if [ -e $i/error ]; then
    l=$i"\t(error: no trace given)"
    echo -e $l
  elif [ -e $i/notpe ]; then
    l=$i"\t(error: no pe file found)"
    echo -e $l
  elif [ -e $i/disasm ]; then
    n_trace=`tail -n 1 $i/$i".trace" |sed 's/_.*//'`
    m_trace=`echo $n_trace"+1"|bc`
    for j in `seq 0 $n_trace`; do
      n=`printf "%02d" $j`
 #     n_conflicts_disasm=`grep remain $i/$i"_"$n.log | sed 's/\ .*//'`
      n_layers_trace=`grep "trace:" $i/$i"_"$n.log | awk '{print $2}'`
      n_disas_jmps_trace=`grep "trace:" $i/$i"_"$n.log | awk '{print $3}'`
      n_conflicts_trace=`grep "trace:" $i/$i"_"$n.log | awk '{print $4}'`
      n_addr_conflicts_trace=`grep "trace:" $i/$i"_"$n.log | awk '{print $5}'`
      
      n_layers_disas=`grep "hybrid:" $i/$i"_"$n.log | awk '{print $2}'`
      n_disas_jmps_disas=`grep "hybrid:" $i/$i"_"$n.log | awk '{print $3}'`
      n_conflicts_disas=`grep "hybrid:" $i/$i"_"$n.log | awk '{print $4}'`
      n_addr_conflicts_disas=`grep "hybrid:" $i/$i"_"$n.log | awk '{print $5}'`

      n_nodes=`grep "initial" $i/$i"_"$n.log|sed 's/\ .*//'`      
      if [ -e $i/$i"_"$n.time ]; then
        ti=`cat $i/$i"_"$n.time`
      else
        ti="/"
      fi
      if [ -z $n_layers_trace ]; then
        l=$i"\t(error: in disasm)"
#	rm $i/disasm
      else
        l=$i"\t"$m_trace"\t"$n"\t"$n_layers_disas"("$n_layers_trace")\t"$n_disas_jmps_disas"("$n_disas_jmps_trace")\t"$n_conflicts_disas"("$n_conflicts_trace")\t"$n_addr_conflicts_disas"("$n_addr_conflicts_trace")\t"$ti"\t"$n_nodes
      fi
      echo -e $l
    done
    echo ''
  else
    l=$i"\t(not done)"
    echo -e $l
  fi
done
