#!/bin/bash


list=`ls | grep tar | sed 's/\.tar.*//'`

for i in `echo $list`; do
	if [ -e $i/$i.trace-w00 ]; then
		n_w=`ls $i/$i.trace-w* 2>/dev/null| wc -l`
		echo $i" has "$n_w" waves."
	else
		echo $i" has no wave (err)."
	fi
done
